import "@/styles/globals.css";
import { Inter } from "next/font/google";
import ToastProvider from "./_components/providers/ToastProvider";
import { TRPCReactProvider } from "@/trpc/react";
import UiProvider from "./_components/providers/NextUiProvider";
import AuthContext from "@/context/AuthContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthContext>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <TRPCReactProvider>
            <ToastProvider />
            <UiProvider>
              <div>{children}</div>
            </UiProvider>
          </TRPCReactProvider>
        </body>
      </html>
    </AuthContext>
  );
}
